name: Build and Publish Electron App

on:
  push:
    branches:
      - master  # or your default branch
  pull_request:

jobs:
  create_release:
    runs-on: windows-latest  # Use Windows environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Read version from package.json using Node.js
      - name: Get version from package.json
        id: version
        run: |
          node -p "require('./package.json').version" > version.txt
          echo "VERSION=$(type version.txt)" >> $env:GITHUB_ENV
        shell: powershell

      # Step 3: Create draft GitHub release using version from package.json
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub token for authentication
        with:
          tag_name: "v1.0.5"  # Version from package.json
          release_name: "v1.0.5"  # Use the same version for the release name
          draft: true  # This ensures the release is created as a draft
          prerelease: false  # Set to true if it's a pre-release

      # Step 2: Set up Node.js (required for Electron)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build and publish the Electron app
      - name: Build and publish
        run: npm run dist  # Or the custom build command you use
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the GH_TOKEN secret for authentication